#include "research/ResearchDefaults.h"
using namespace ResearchDefaults;
#include "TestApplication.h"
#include <cstdio>
#include <cstdlib>

void PrintTestUsage() {
    std::printf(
        "usage: GunBrosTests [options]\n"
        "\n"
        "  --intro                   play original Glu video (space/click to skip)\n"
        "  --skip-intro              enter menus without the startup video\n"
        "  --media-check             decode all original music and intro frames\n"
        "  --movie-check             original Glu timelines and Powerup border pixels\n"
        "  --fontbitmap              render all BIG fonts and export their original PNG atlases\n"
        "  --movie <0..147>           inspect original UI; arrows browse, C regions\n"
        "  --movie-gallery           render every original core UI movie\n"
        "  --movie-regions           outline the user regions that define the original layout\n"
        "  --test-output <absolute>  case artifacts (default: tests/out/manual)\n"
        "  --help, -h                show available options and exit\n"
        "  --mute                    disable sound playback for every mode\n"
        "  --game                    planets, equipment, shop and local profile\n"
        "  --menu-page <0..29>       menu screenshot page (25: first brother selection)\n"
        "  --hud-check              original combat HUD, overlays and input check\n"
        "  --profile <directory>    use separate original DataStore files (.dat: legacy study)\n"
        "  --progress-check          verify progression, purchases and refinery\n"
        "  --profile-play-check      play, save, reload and resume test account\n"
        "  --play                    retail survival; default pack2 map7\n"
        "  --survival-check          real-map projectile/wave integration check\n"
        "  --brother-check           AI-only firing, death and wave revival check\n"
        "  --brother                 add the original AI follow/aim policy to --play\n"
        "  --game-menu-check         original navigation, help, social, promotions and transitions\n"
        "  --store-card-check        verify GUNS/ARMOR/POWER UPS cards and capture stages\n"
        "  --upgrade-popup-check     verify original mastery playback and purchase\n"
        "  --native-profile-check    verify original DataStore files and new profile\n"
        "  --native-profile-play-check original equipment, waves and native save reload\n"
        "  --bank-check        original bank cards, prompt and native save reload\n"
        "  --options-check     original list, preferences and native save reload\n"
        "  --social-check      offline/local social UI, matchmaking and IAP callbacks\n"
        "  --planet-menu-check original map, mode overlay and four retail selections\n"
        "  --mission-menu-check original mission cards, requirements and wave selection\n"
        "  --play-interaction-check  verify selection, mode effects, back and scrolling\n"
        "  --header-check      original navigation, meters, entrance and input\n"
        "  --refinery-menu-check original refinery layout, transfers and native saving\n"
        "  --greeting-check original greeting animation and exit-time daily rewards\n"
        "  --player-select-check original brother selection and native save\n"
        "  --original-hud-check original regions, meters and control sprites\n"
        "  --powerup-selector-check original in-game selector and native purchase\n"
        "  --pause-check original pause list, help and native preferences\n"
        "  --postgame-menu-check original wrapup with actual native survival results\n"
        "  --store-template-check    verify BIG store filter and shared item cards\n"
        "  --ui-feedback-check       verify splash, package purchase and store badges\n"
        "  --package-purchase-check  verify package delivery, equipment and restart\n"
        "  --daily-bonus-check       original rewards, calendar cycle and save checks\n"
        "  --tutorial-check          original move, fire, swap and grenade tutorial\n"
        "  --loading-wipe-check original CG/STR pairs and two-region menu wipe\n"
        "  --promotion-check original Invite / Free Warbucks modal flow\n"
        "  --scene-transition-check  verify logo/menu/game share a window and GL context\n"
        "  --dialog-check            original BIG dialog playback and completion\n"
        "  --dual-weapon-check       both equipped stamps, distinct slots, save reload\n"
        "  --combat-feedback-check   spire, authored health bars, hits and silent audio burst checks\n"
        "  --boss-check              four retail Boss cameras, grenade armor and wave return\n"
        "  --map-occlusion-check     real obstacle/player front and back pixels\n"
        "  --player-death-check      original slow motion, death completion and stsuicide\n"
        "  --local-live-check        local bot, co-op combat, revive and practice isolation\n"
        "  --performance-check       record 1200 real gameplay frames to CSV\n"
        "  --spawn-performance-check profile wave 50 at the reported slow position\n"
        "  --spawn-performance-realtime-check use the normal catch-up loop for 1200 updates\n"
        "  --path-cache-check        check repeated routes, locks and graph reload\n"
        "  --flock-check             check separation using real BIG enemies\n"
        "  --flock-performance-check replay pack7 wave 50 crowd movement\n"
        "  --disable-flock           disable separation for a test-only A/B replay\n"
        "  --uncached-paths          use the old search in a spawn performance A/B replay\n"
        "  --pickup-check            pickup templates and collection scripts\n"
        "  --pickup-render-check     all pickup sprites and animation frames\n"
        "  --prop-check              complete prop templates and native callbacks\n"
        "  --prop-combat-check       isolated barrel explosions on both maps\n"
        "  --actor-feedback-check    knockback audio and animated AI weapon swaps\n"
        "  --powerup-check           consumable templates, queries and actions\n"
        "  --powerup-study           playable item lab, isolated stock\n"
        "  --powerup-play-check      inventory, XP float/fade and Airstrike frame check\n"
        "  --mission-check           archive mission, objective and level references\n"
        "  --original-save-check     read original data stores without modifying them\n"
        "  --original-profile       alias for the default original DataStore account\n"
        "  --original-profile-check validate import, original equipment and play/reload\n"
        "  --horde [0-9]            play BOKOR with original Horde script\n"
        "  --horde-check [0-9]      actual combat through one Horde\n"
        "  --campaign <pack> <n>     play original unfinished campaign mission\n"
        "  --campaign-check <pack> <n>  movement/combat smoke test in archived mission\n"
        "  --check-waves <n>         number of waves to play in survival check\n"
        "  --start-wave <1..500>     wave study / saved-progress starting point\n"
        "  --armor-check             verify every armor template, script and asset\n"
        "  --armor-render-check      render all armor with three weapon poses\n"
        "  --level-flow-check        simulate original level spawn/death events\n"
        "  --armor [n]               armor viewer; combine with --arena to fight\n"
        "  --m1                      M1: verify cross-pack resource addressing\n"
        "  --m2                      M2: show a single PNG from a .big\n"
        "  --dump <pack>             list one pack's resource table\n"
        "  --maps                    list every map, in the viewer's order\n"
        "  --levels                  list which levels scroll a tile layer\n"
        "  --meshes                  parse every 3D model and list what is in it\n"
        "  --movesets                follow every model to the atlas it wears\n"
        "  --mesh <n>                M3.5: show model <n> of the catalogue\n"
        "  --character [n]           M3.7: the player, his legs, and gun <n>\n"
        "  --player-weapon [n]       weapon preview: 1-7 category, N/M weapon\n"
        "  --weapons                 list weapon templates and holding overrides\n"
        "  --weapon-check            verify all weapon models and input transitions\n"
        "  --postgame-presentation-check  verify icon sparkles and instant tabs\n"
        "  --audio-transitions-check  store move sounds and menu/battle music handoffs\n"
        "  --weapon-effects-check    laser continuity, ray collision and projectile visuals\n"
        "  --mine-check              mine recycling, boundary explosions and authored lifetime\n"
        "  --arena [n]               combat arena for enemy template n\n"
        "  --arena-check             verify enemy catalogue and combat contracts\n"
        "  --weapon <n>              initial weapon in --gameview / --arena\n"
        "  --fire                    hold fire during preview / screenshot\n"
        "  --enemy <n>               M3.8: enemy <n>, assembled by its script\n"
        "  --enemies                 run every enemy script, list its parts\n"
        "  --enemyanim <n>           M3.8: enemy <n>, M/N walking the script's\n"
        "                            states -- its real idle/attack/death\n"
        "  --enemyanims              list every enemy's states and the moves\n"
        "                            each one chains\n"
        "  --move <n>                M3.8: hold body move <n> instead of the\n"
        "                            one the script chose, and loop it\n"
        "  --state <n>               M3.8: enter state <n> and let its whole\n"
        "                            sequence play\n"
        "  --spawns                  M3: start with the spawn overlay on\n"
        "  --collisions              M4: start with collision edges visible\n"
        "  --gameview                open the map as a playable fixed view\n"
        "  --map <pack> <n>          which map M3 should START on; the arrow\n"
        "                            keys reach every other one\n"
        "                            (default: %s %u)\n"
        "  --image <pack> <id>       which PNG M2 should display\n"
        "                            (default: %s %u)\n"
        "  --big <directory>         where the .big files are (XGA or plain TOC)\n"
        "  --big-version             inspect auto-detected BigVersion 1/2/3\n"
        "                            (default: EXE-directory/big)\n"
        "  --screenshot <file.png>   save the first frame and exit\n"
        "  --advance <ms>            run the animations on this far before\n"
        "                            that first frame\n",
        kDefaultMapPack, kDefaultMapIndex, kDefaultImagePack, kDefaultImageResourceId);
}

