#include "gun_bros_re/debug/Capture.h"
#include "gun_bros_viewer/ViewerControls.h"
#include "gun_bros_viewer/ViewerSettings.h"
#include "gun_bros_viewer/scenes/ArenaPreviewInternal.h"
#include "gun_bros_viewer/scenes/ArenaTools.h"
#include "gun_bros_re/data/ZStoreCatalog.h"
#include "gun_bros_re/debug/CollisionOverlay.h"
namespace ArenaDetail {
constexpr float kRadians = 3.14159265f / 180;
const char *const kShaders = Paths::Shaders().c_str();

bool Equip(ZPackTables &tables, const ZPlayerTemplateData &data, const ZWeaponEntry &entry,
    ZPlayerModel &player, const ZShaderProgram &program) {
    return EquipPlayerWeapon(tables, data.script, entry.data, entry.owner, player) &&
        CreatePlayerBuffers(player, program);
}

}

using namespace ArenaDetail;

int RunArena(const std::string &bigDirectory, std::uint32_t enemyIndex,
    std::uint32_t weaponIndex, const std::string &screenshot, std::uint32_t advanceMs,
    bool fire, bool showCollisions, int armorIndex, ArenaSceneCallback onSceneReady) {
    CResTOCManager toc;
    if (!toc.InitAuto(bigDirectory) || !toc.Bind()) { return 1; }
    ZPackTables tables(toc);
    std::vector<ZEnemyTemplateData> catalog;
    std::vector<ZWeaponEntry> weapons;
    ZPlayerTemplateData playerData;
    ZPlayerVitals vitals;
    if (!LoadEnemyCatalog(toc, tables, catalog) || catalog.empty() ||
        !LoadWeaponCatalog(toc, tables, weapons) || !FindPlayerTemplate(toc, tables, playerData) ||
        !LoadInitialPlayerHealth(toc, tables, vitals.maximum)) { return 1; }
    if (weapons.empty() || weaponIndex >= weapons.size() || enemyIndex >= catalog.size()) {
        std::printf("[arena] equipment or enemy index out of range\n"); return 1;
    }
    ZWindow window;
    if (!OpenViewerWindow(window, "Arena")) { return 1; }

    ViewerControls controls(window, arena::Bindings);
    if (!controls.Init()) { return 1; }
    ZShaderProgram program, markerProgram;
    if (!program.Load(kShaders, "ogles_vs_mvp_tex0", "ogles_ps_tex0") ||
        !markerProgram.Load(kShaders, "ogles_vs_mvp_constcolor", "ogles_ps_constcolor")) { return 1; }
    ZMarkerBatch markers;
    if (!markers.Create(markerProgram)) { return 1; }
    ZPlayerModel player;
    player.vitals = &vitals;
    std::size_t weapon = weaponIndex % weapons.size();
    std::size_t entry = enemyIndex % catalog.size();
    if (!BuildPlayerBody(tables, playerData.moveSet, player) ||
        !Equip(tables, playerData, weapons[weapon], player, program)) { return 1; }
    CLevel scene(toc, tables, program);
    scene.BindCombat(catalog, player, vitals, playerData.gameScale);
    
    if (onSceneReady != nullptr) {
        ArenaScene ready{window, toc, tables, program, catalog, weapons, playerData, player, vitals, scene};
        return onSceneReady(ready);
    }

    std::array<ZPowerupEntry, 3> grenades;
    if (!LoadArenaGrenades(toc, tables, grenades)) { return 1; }
    std::vector<std::string> enemyNames;
    for (const auto &enemy : catalog) {
        std::string name = ReadGameString(toc, enemy.name);
        if (name.empty()) { name = "UNKNOWN NAME"; }
        enemyNames.push_back(name);
    }
    vitals.invincible = false;
    vitals.unlimitedHealth = true;
    ArenaCamera camera;
    if (armorIndex >= 0) {
        std::vector<ZArmorEntry> armor;
        if (!LoadArmorCatalog(toc, tables, armor) || armorIndex >= static_cast<int>(armor.size()) ||
            !EquipPlayerArmor(tables, armor[armorIndex].data, program, player)) {
            return 1;
        }
    }
    scene.Reset();
    scene.Spawn(entry, 600, 330);
    for (std::uint32_t time = 0; time < advanceMs; time += kStepMs) {
        scene.Update(kStepMs, 0, 0, fire);
    }
    // Input help is generated by ViewerControls from ViewerBindings.h.
    bool paused = false;
    bool collisions = showCollisions;
    std::uint64_t previous = window.GetTicksMs();
    int accumulator = 0;
    std::uint64_t noticeUntil = 0;
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    while (controls.PumpEvents()) {
        bool step = false;
        bool reset = false;
        std::size_t nextEntry = entry;
        std::size_t nextWeapon = weapon;
        for (ZKeyCode key = controls.TakeKeyPress(); key != ZKeyCode::None; key = controls.TakeKeyPress()) {
            if (controls.IsPressed(key, ViewerAction::Previous)) { nextEntry = (nextEntry + catalog.size() - 1) % catalog.size(); }
            else if (controls.IsPressed(key, ViewerAction::Next)) { nextEntry = (nextEntry + 1) % catalog.size(); }
            else if (controls.IsPressed(key, ViewerAction::Spawn)) {
                if (scene.SpawnNearby(entry) == nullptr) { noticeUntil = window.GetTicksMs() + 2500; }
            }
            else if (controls.IsPressed(key, ViewerAction::ResetBattle)) { reset = true; }
            else if (controls.IsPressed(key, ViewerAction::Grenade)) { ThrowArenaGrenade(player.weapon->brother, grenades[0]); }
            else if (controls.IsPressed(key, ViewerAction::FreezeGrenade)) { ThrowArenaGrenade(player.weapon->brother, grenades[1]); }
            else if (controls.IsPressed(key, ViewerAction::ShockGrenade)) { ThrowArenaGrenade(player.weapon->brother, grenades[2]); }
            else if (controls.IsPressed(key, ViewerAction::ResetView)) { camera.zoom = kDefaultZoom; }
            else if (controls.IsPressed(key, ViewerAction::Pause)) { paused = !paused; accumulator = 0; scene.SetPaused(paused); }
            else if (controls.IsPressed(key, ViewerAction::Step)) { paused = true; step = true; scene.SetPaused(true); }
            else if (controls.IsPressed(key, ViewerAction::Collisions)) { collisions = !collisions; }
            else { nextWeapon = SelectWeaponKey(weapons, nextWeapon, controls.WeaponSelectionKey(key)); }
        }
        if (nextEntry != entry || reset) {
            entry = nextEntry;
            scene.Reset();
            scene.Spawn(entry, 600, 330);
            accumulator = 0;
        }
        if (nextWeapon != weapon && !vitals.dead) {
            // Release the old gun's continuous effects; enemy attacks and
            // already launched projectiles keep their independent lifetimes.
            scene.RetireOwner(kPlayerCombatId);
            if (Equip(tables, playerData, weapons[nextWeapon], player, program)) { weapon = nextWeapon; }
        }
        int width = 0, height = 0;
        controls.GetDrawableSize(width, height);
        // Keep the arena's world proportions when the dock narrows the viewport.
        // A separate screen-space header leaves the whole remaining area usable.
        const int arenaWidth = std::max(1, width);
        const int arenaTop = std::min(kInfoHeight, height / 2);
        const int arenaHeight = std::max(1, height - arenaTop);
        camera.Scroll(controls.TakeWheelDelta());
        camera.Follow(scene.GetPlayer().x, scene.GetPlayer().y, arenaWidth, arenaHeight);
        float mouseX = 0, mouseY = 0;
        const bool pointerInArena = controls.GetMousePosition(mouseX, mouseY) &&
            mouseX >= 0 && mouseX < arenaWidth &&
            mouseY >= arenaTop && mouseY < arenaTop + arenaHeight;
        if (screenshot.empty() && pointerInArena && !vitals.dead) {
            scene.GetPlayer().facing = std::atan2(camera.WorldX(mouseX) - scene.GetPlayer().x,
                scene.GetPlayer().y - camera.WorldY(mouseY - arenaTop)) / kRadians;
        }
        float moveX = 0, moveY = 0;
        if (controls.IsDown(ViewerAction::MoveLeft)) { moveX -= 1; }
        if (controls.IsDown(ViewerAction::MoveRight)) { moveX += 1; }
        if (controls.IsDown(ViewerAction::MoveUp)) { moveY -= 1; }
        if (controls.IsDown(ViewerAction::MoveDown)) { moveY += 1; }
        const std::uint64_t now = window.GetTicksMs();
        if (!paused && screenshot.empty()) { accumulator += static_cast<int>(std::min<std::uint64_t>(now - previous, 100)); }
        previous = now;
        if (step) { accumulator = kStepMs; }
        while (accumulator >= kStepMs) {
            scene.Update(kStepMs, moveX, moveY, fire || (pointerInArena && controls.IsDown(ViewerAction::Fire)));
            accumulator -= kStepMs;
        }
        float projection[16];
        camera.Follow(scene.GetPlayer().x, scene.GetPlayer().y, arenaWidth, arenaHeight);
        Matrix4dOrthoTopLeft(arenaWidth / camera.scale, arenaHeight / camera.scale, 4000, projection);
        Matrix4dTranslate(projection, -camera.x, -camera.y);
        glViewport(0, 0, arenaWidth, arenaHeight);
        glClearColor(0, 0, 0, 1);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        glDisable(GL_DEPTH_TEST);
        // The movement clamp limits the player's center. Expand by its collision
        // radius so the visible wall touches the player when movement stops.
        const auto bounds = scene.GetPlayerMovementBounds();
        const float radius = scene.GetPlayerRadius();
        const float left = bounds.left - radius, right = bounds.right + radius;
        const float top = bounds.top - radius, bottom = bounds.bottom + radius;
        const float borderWidth = 2 / camera.scale;
        markers.Begin();
        markers.AddSegment(left, top, right, top, borderWidth);
        markers.AddSegment(right, top, right, bottom, borderWidth);
        markers.AddSegment(right, bottom, left, bottom, borderWidth);
        markers.AddSegment(left, bottom, left, top, borderWidth);
        markers.Draw(markerProgram, projection, 0.12f, 0.48f, 1, 1);
        float playerMatrix[16], model[16], mvp[16];
        scene.PlayerMatrix(playerMatrix);
        scene.Draw(projection, nullptr, 1, ZWeaponDrawPass::BehindPlayer);
        // Actor meshes share a depth buffer; UI and billboards are layered after.
        glEnable(GL_DEPTH_TEST);
        for (auto &actor : scene.GetEnemies()) {
            if (actor->model.enemy.combat.removed) { continue; }
            scene.EnemyMatrix(*actor, model);
            Matrix4dMultiply(projection, model, mvp);
            mvp[3] += 2.0f * actor->model.enemy.stun.GetOffset() / width;
            DrawEnemyModel(actor->model, program, mvp);
        }
        Matrix4dMultiply(projection, playerMatrix, mvp);
        DrawPlayer(player, program, mvp);
        scene.Draw(projection, nullptr, 1, ZWeaponDrawPass::InFrontOfPlayer);
        glDisable(GL_DEPTH_TEST);
        // Every bar uses the same predicate as projectile damage filtering.
        for (auto &actor : scene.GetEnemies()) {
            CEnemy &enemy = actor->model.enemy;
            const CEnemy::CombatState &state = enemy.combat;
            if (state.removed || state.dead) { continue; }
            float barY = state.y - std::max(60.0f, actor->data->gameScale * 0.55f);
            markers.Begin();
            markers.AddRect(state.x - 34, barY, 68, 8);
            markers.Draw(markerProgram, projection, 0.01f, 0.015f, 0.02f, 1);
            markers.Begin();
            float fraction = 0;
            if (state.maxHealth > 0) { fraction = std::clamp(state.health / state.maxHealth, 0.0f, 1.0f); }
            markers.AddRect(state.x - 32, barY + 2, 64 * fraction, 4);
            if (!state.enabled) { markers.Draw(markerProgram, projection, 0.5f, 0.5f, 0.5f, 1); }
            else if (enemy.CanReceiveProjectile(0, kPlayerCombatId)) { markers.Draw(markerProgram, projection, 0.95f, 0.23f, 0.2f, 1); }
            else { markers.Draw(markerProgram, projection, 0.22f, 0.95f, 0.5f, 1); }
            char health[64];
            std::snprintf(health, sizeof(health), "%.0f/%.0f", state.health, state.maxHealth);
            float labelProjection[16];
            Matrix4dOrthoTopLeft(static_cast<float>(arenaWidth), static_cast<float>(arenaHeight), 1, labelProjection);
            controls.DrawLabel(health, (state.x - 32 - camera.x) * camera.scale,
                (barY - camera.y) * camera.scale - 26, 160, 18, labelProjection);
        }
        if (collisions) {
            DrawCollisionOverlay(markers, markerProgram, projection, 1 / camera.scale, nullptr, &scene, nullptr, &scene);
        }
        // Diagnostic information is screen-space host UI, independent of zoom.
        glViewport(0, 0, width, height);
        float hudProjection[16];
        const float hudScale = arenaTop / static_cast<float>(kInfoHeight);
        const int hudWidth = static_cast<int>(width / hudScale);
        Matrix4dOrthoTopLeft(width / hudScale, height / hudScale, 4000, hudProjection);
        markers.Begin();
        markers.AddRect(0, 0, static_cast<float>(hudWidth), kInfoHeight);
        markers.Draw(markerProgram, hudProjection, 0, 0, 0, 1);
        markers.Begin();
        markers.AddRect(16, kInfoHeight - 2, static_cast<float>(hudWidth - 32), 1);
        markers.Draw(markerProgram, hudProjection, 0.18f, 0.38f, 0.48f, 1);
        unsigned kills = scene.kills, hits = scene.hits;
        float damage = scene.damageDealt;
        unsigned deferred = 0;
        for (const auto &actor : scene.GetEnemies()) {
            const CEnemy::CombatState &state = actor->model.enemy.combat;
            kills += state.deathCount; hits += state.hitCount;
            damage += state.totalDamage;
            deferred |= state.deferredMechanisms;
        }
        char line[256];
        int fontHeight = 22;
        if (hudWidth < 600) { fontHeight = 18; }
        controls.DrawLabel("Enemy - " + enemyNames[entry], 16, 6, hudWidth - 32, 26, hudProjection);
        const char *playState = "Live";
        if (paused) { playState = "Paused"; }
        std::snprintf(line, sizeof(line), "%zu/%zu  %s  %s  Zoom %.0f%%", entry, catalog.size() - 1,
            catalog[entry].owner.c_str(), playState, camera.zoom * 100);
        controls.DrawLabel(line, 16, 38, hudWidth - 32, fontHeight, hudProjection);
        controls.DrawLabel(WeaponSelectionLabel(weapons, weapon), 16, 62, hudWidth - 32, fontHeight, hudProjection);
        std::snprintf(line, sizeof(line), "HP unlimited   Received hits %u", vitals.hits);
        controls.DrawLabel(line, 16, 86, hudWidth - 32, fontHeight, hudProjection);
        std::snprintf(line, sizeof(line), "Taken %.1f   Last hit %.1f", vitals.incomingDamage, vitals.lastDamage);
        controls.DrawLabel(line, 16, 110, hudWidth - 32, fontHeight, hudProjection);
        std::snprintf(line, sizeof(line), "Dealt %.1f   Last hit %.1f", damage, scene.lastDamage);
        controls.DrawLabel(line, 16, 134, hudWidth - 32, fontHeight, hudProjection);
        std::snprintf(line, sizeof(line), "Alive %zu   Kills %u   Landed hits %u", scene.AliveCount(), kills, hits);
        controls.DrawLabel(line, 16, 158, hudWidth - 32, fontHeight, hudProjection);
        if (!scene.GetEnemies().empty()) {
            const CEnemy::CombatState &state = scene.GetEnemies().front()->model.enemy.combat;
            std::snprintf(line, sizeof(line), "Filter %d   Target type %d", state.variables[16], state.targetType);
            controls.DrawLabel(line, 16, kInfoHeight + 8, hudWidth - 32, fontHeight, hudProjection);
        }
        if ((deferred & 3) != 0) { controls.DrawLabel("Boss / level mechanisms deferred", 16, kInfoHeight + 36, hudWidth - 32, fontHeight, hudProjection); }
        if (now < noticeUntil) { controls.DrawLabel("No free spawn position", 16, kInfoHeight + 92, hudWidth - 32, fontHeight, hudProjection); }
        if (!catalog[entry].script.IsPresent()) { controls.DrawLabel("Unused - no script", 16, kInfoHeight + 64, hudWidth - 32, fontHeight, hudProjection); }
        else if (catalog[entry].gameScale == 0) { controls.DrawLabel("No visible model", 16, kInfoHeight + 64, hudWidth - 32, fontHeight, hudProjection); }
        window.SetTitle(ViewerWindowTitle("Arena", enemyNames[entry] + " | " + catalog[entry].owner + " | " + weapons[weapon].name));
        if (!controls.Draw()) { return 1; }
        if (!screenshot.empty()) {
            if (Capture::SaveFrame(window, screenshot)) { return 0; }
            return 1;
        }
        window.Present();
    }
    return 0;
}
