#pragma once
/** Shared map/session include surface. Behavior lives in the original owners. */
#define NOMINMAX
#include "gun_bros_re/gameplay/map/CRenderQueue.h"
#include "engine/core/ZPaths.h"
#include "gun_bros_re/gameplay/map/CMapResources.h"
#include "gun_bros_re/gameplay/map/CLevelProps.h"
#include "engine/core/CStringToKey.h"
#include "gun_bros_re/gameplay/game/CGameSession.h"
#include "gun_bros_re/gameplay/audio/CBGM.h"
#include "gun_bros_re/gameplay/enemy/CEnemy.h"
#include "gun_bros_re/gameplay/brother/CBrother.h"
#include "gun_bros_re/gameplay/weapon/CGun.h"
#include "gun_bros_re/gameplay/armor/CArmor.h"
#include "gun_bros_re/gameplay/game/CGame.h"
#include "gun_bros_re/gameplay/collision/Collision.h"
#include "gun_bros_re/debug/CollisionOverlay.h"
#include "gun_bros_re/data/store/CStoreItem.h"
#include <sstream>
#include <chrono>
#include "gun_bros_re/gameplay/game/CGameFlow.h"
#include "gun_bros_re/data/profile/CProfileManager.h"
#include "gun_bros_re/ui/host/ZLoadingScreen.h"
#include "gun_bros_re/host/ZHostSettings.h"
#include "gun_bros_re/ui/hud/CInputPad.h"
#include "gun_bros_re/data/mission/Mission.h"
#include "gun_bros_re/gameplay/level/CLevel.h"
#include "gun_bros_re/data/objects/CGunBros.h"
#include "engine/resources/CArrayInputStream.h"
#include "engine/platform/ZAudioPlayer.h"
#include "engine/graphics/ZMarkerBatch.h"
#include "engine/core/ZMatrix4d.h"
#include "engine/graphics/ZPNG.h"
#include "engine/graphics/ZQuadBatch.h"
#include "engine/graphics/ZShaderProgram.h"
#include "engine/graphics/ZTexture.h"
#include "engine/platform/ZWindow.h"
#include <SDL3/SDL_events.h>
#include "engine/platform/ZGLLoader.h"
#include "gun_bros_re/data/objects/CGameObjectPack.h"
#include "gun_bros_re/data/objects/CGameAssetRef.h"
#include "gun_bros_re/gameplay/map/CLayerObject.h"
#include "gun_bros_re/gameplay/map/CLayerTile.h"
#include "gun_bros_re/gameplay/map/CMap.h"
#include "gun_bros_re/effects/CParticleEffect.h"
#include "gun_bros_re/gameplay/map/CProp.h"
#include "engine/resources/CResTOCManager.h"
#include "gun_bros_re/gameplay/map/TileSet.h"
#include "engine/glu/sprite/CSpriteGlu.h"
#include "engine/glu/sprite/CSpriteIterator.h"
#include "engine/glu/sprite/CSpritePlayer.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <map>
#include <memory>
#include <vector>
#include "gun_bros_re/gameplay/map/CMapEffects.h"
#include "gun_bros_re/gameplay/map/CCameraDrawing.h"
#include "gun_bros_re/gameplay/map/CLayerObjectPlayers.h"
