"""从 ARMv7 菜单描述符导出加载页绑定和原生卡片字串；不复制 BIG 内容。"""
from pathlib import Path
import hashlib
import json
import struct
from extract_menu_statics import read_image

ROOT = Path(__file__).resolve().parents[2]


def main():
    """地址来自 CMenuSplash::Init 和 CMenuTapjoyOption::Bind 的消费者。"""
    data, segments = read_image()

    def offset_of(address):
        for start, size, offset in segments:
            if start <= address < start + size:
                return offset + address - start
        raise ValueError(f"Unmapped address {address:x}")

    def read_name(address):
        offset = offset_of(address)
        return data[offset:data.index(0, offset)].decode('utf-8')

    lines = [
        '// Generated by src/tools/extract_ui_transition_statics.py; do not edit.',
        f'// gunbros SHA256: {hashlib.sha256(data).hexdigest()}',
        '// CMenuSplash::Init :160386; native descriptor at ARMv7 VA 0x403230.',
    ]
    words = struct.unpack_from('<13I', data, offset_of(0x403230))
    lines.append('inline constexpr const char *kSplashMovie = ' + json.dumps(read_name(words[1])) + ';')
    lines.append('inline constexpr const char *kSplashCaption = ' + json.dumps(read_name(words[2])) + ';')
    lines.append('inline constexpr unsigned kSplashImageAlignment = ' + str(words[6]) + ';')
    # CMenuSplash::Init reads descriptor+44 as the exit-animation flag.
    for address, name in ((0x4031f0, 'kSplashEnterAnimateExit'), (0x403230, 'kSplashReturnAnimateExit')):
        value = data[offset_of(address) + 44]
        lines.append(f'inline constexpr bool {name} = {value};')
    for address, name in ((0x3c6188, 'kFreeCardTop'), (0x3c61ac, 'kFreeCardBottom')):
        text = data[offset_of(address):offset_of(address) + 36].decode('utf-32-le').rstrip('\0')
        lines.append(f'// CMenuTapjoyOption::Bind :222059, native UTF-32 literal at VA {address:#x}.')
        lines.append(f'inline constexpr const char *{name} = ' + json.dumps(text) + ';')
    target = ROOT / 'src/gun_bros_re/runtime/OriginalSplashData.inc'
    target.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
